#include<stdio.h>
#include<stdlib.h>
#include<time.h>
/*
 * Description: main - Entry point
 *
 * Variable n: holds random number generated by srand()
 *
 * Returns: 0 (Success)
 */
int main(void)
{
	int n;
	srand(time(0));
	n = rand();
	if (n > 0)
	{
		printf("%d is positive\n",n);
	}
	else if (n < 0)
	{
		printf("%d is negative\n",n);
	}
	else
	{
		printf("%d is zero\n",n);
	}
	return(0);
}
